---
apiVersion: v1
kind: Namespace
metadata:
  name: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-headless
  namespace: zookeeper
  labels:
    app: zookeeper
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: tcp-peers
    port: 2888
    protocol: TCP
    targetPort: tcp-peers
  - name: tcp-leader
    port: 3888
    protocol: TCP
    targetPort: tcp-leader
  selector:
    app: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  ports:
  - name: http-admin
    port: 8080
    protocol: TCP
    targetPort: http-admin
  - name: tcp-client
    port: 2181
    protocol: TCP
    targetPort: tcp-client
  selector:
    app: zookeeper
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: zookeeper-pdb
  namespace: zookeeper
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: zookeeper
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: zookeeper
spec:
  selector:
    matchLabels:
      app: zookeeper
  serviceName: zookeeper-headless
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        imagePullPolicy: IfNotPresent
        image: "myzoo:1.0"
        resources:
          requests:
            memory: "2Gi"
            cpu: "0.5"
          limits:
            memory: "3Gi"
            cpu: "0.5"
        env:
        - name: K8S_ZOO_REPLICAS
          value: "3"
        ports:
        - name: tcp-client
          containerPort: 2181
        - name: tcp-peers
          containerPort: 2888
        - name: tcp-leader
          containerPort: 3888
        - name: http-admin
          containerPort: 8080
        volumeMounts:
        - name: datadir
          mountPath: /data
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
