---
apiVersion: v1
kind: Namespace
metadata:
  name: kafka-k8s
---
apiVersion: v1
kind: Service
metadata:
  name: zk-hs
  namespace: kafka-k8s
  labels:
    app: zk
spec:
  clusterIP: None
  ports:
  - port: 2888
    protocol: TCP
    name: peer-comms
  - port: 3888
    protocol: TCP
    name: leader-election
  - port: 2181
    protocol: TCP
    name: client
  selector:
    app: zk
---
apiVersion: v1
kind: Service
metadata:
  name: zk-cs
  namespace: kafka-k8s
  labels:
    app: zk
spec:
  ports:
  - port: 2181
    protocol: TCP
    name: client
  - port: 8080
    protocol: TCP
    name: admin
  type: LoadBalancer
  selector:
    app: zk
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: zk-pdb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: zk
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk
  namespace: kafka-k8s
spec:
  selector:
    matchLabels:
      app: zk
  serviceName: zk-hs
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: zk
    spec:
      containers:
      - name: k8s-zookeeper
        imagePullPolicy: IfNotPresent
        image: "myzoo:1.0"
        resources:
          requests:
            memory: "2Gi"
            cpu: "0.5"
          limits:
            memory: "3Gi"
            cpu: "0.5"
        env:
        - name: K8S_ZOO_REPLICAS
          value: "3"
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: peer-comms
        - containerPort: 3888
          name: leader-election
        - containerPort: 8080
          name: admin
        volumeMounts:
        - name: datadir
          mountPath: /data
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
