---
# tasks file for zookeeper
- name: ensure dependencies are installed
  package:
    name: "{{ zookeeper_dependecies }}"
    state: present
  with_items:
    - zookeeper_dependecies

- name: ensure group zookeeper exists
  group:
    name: zookeeper
    gid: "{{ zookeeper_user.gid }}"
    state: present

- name: ensure user zookeeper exists
  user:
    name: zookeeper
    group: zookeeper
    uid: "{{ zookeeper_user.uid }}"
    comment: Zookeeper
    state: present

- name: ensure /opt directory exist
  file:
    path: /opt/
    owner: root
    group: root
    mode: '0755'
    state: directory

- name: ensure necessary directories exist
  file:
    path: "{{ item }}"
    owner: zookeeper
    group: zookeeper
    mode: '0750'
    state: directory
  loop:
    - "{{ zookeeper_data_dir }}"
    - "{{ zookeeper_data_log_dir }}"

- name: ensure latest tarball is fetch
  get_url:
    url: "{{ zookeeper_tarball_url }}"
    dest: "/opt/{{ zookeeper_tarball }}"
    owner: zookeeper
    group: zookeeper
    mode: '0440'
    checksum: "{{ zookeeper_tarball_checksum }}"

- name: extract tarball
  unarchive:
    src: "/opt/{{ zookeeper_tarball }}"
    dest: /opt
    owner: zookeeper
    group: zookeeper
    remote_src: yes
  notify: restart zookeeper service

- name: fix permissions after extract
  file:
    path: "{{ zookeeper_home_dir }}"
    owner: zookeeper
    group: zookeeper
    recurse: yes

- name: ensure setup file is in-place
  template:
    src: zoo.cfg.j2
    dest: "{{ zookeeper_conf_dir}}/zoo.cfg"
    owner: zookeeper
    group: zookeeper
    mode: '0640'
  notify: restart zookeeper service

- name: ensure myid file is in-place
  template:
    src: myid.j2
    dest: "{{ zookeeper_data_dir }}/myid"
    owner: zookeeper
    group: zookeeper
    mode: '0440'

- name: setup systemctl zookeeper service
  template:
    src: zookeeper.service.j2
    dest: /etc/systemd/system/zookeeper.service
    owner: root
    group: root
    mode: '0644'
  notify: restart zookeeper service

- name: ensure zookeeper service is enabled and started
  service:
    name: zookeeper
    state: started
    enabled: yes
    daemon_reload: yes
  register: zookeeper_service